# Form implementation generated from reading ui file 'D:\Python\pythonProject\Bai` Hoc\ChanLe\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/kien0/OneDrive - zxcvb/Pictures/siu.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelName = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(120, 20, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelName.setFont(font)
        self.labelName.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 255);")
        self.labelName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelName.setObjectName("labelName")
        self.labelinputN = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelinputN.setGeometry(QtCore.QRect(90, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelinputN.setFont(font)
        self.labelinputN.setObjectName("labelinputN")
        self.lineEditN = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditN.setGeometry(QtCore.QRect(190, 130, 521, 41))
        self.lineEditN.setObjectName("lineEditN")
        self.labelPrimeNumber = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPrimeNumber.setGeometry(QtCore.QRect(40, 260, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPrimeNumber.setFont(font)
        self.labelPrimeNumber.setObjectName("labelPrimeNumber")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 340, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditPrimeNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPrimeNumber.setGeometry(QtCore.QRect(200, 260, 521, 41))
        self.lineEditPrimeNumber.setObjectName("lineEditPrimeNumber")
        self.lineEditEvenNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEvenNumber.setGeometry(QtCore.QRect(202, 341, 521, 41))
        self.lineEditEvenNumber.setObjectName("lineEditEvenNumber")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 410, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditOddNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditOddNumber.setGeometry(QtCore.QRect(200, 420, 521, 41))
        self.lineEditOddNumber.setObjectName("lineEditOddNumber")
        self.pushButtonOk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOk.setGeometry(QtCore.QRect(380, 200, 93, 28))
        self.pushButtonOk.setObjectName("pushButtonOk")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TranDucTrungKien"))
        self.labelName.setText(_translate("MainWindow", "Tinh Dum Tao"))
        self.labelinputN.setText(_translate("MainWindow", "Input N:"))
        self.labelPrimeNumber.setText(_translate("MainWindow", "Prime Number:"))
        self.label_4.setText(_translate("MainWindow", "Even Number:"))
        self.label_5.setText(_translate("MainWindow", "Odd Number:"))
        self.pushButtonOk.setText(_translate("MainWindow", "Ok"))
