# Form implementation generated from reading ui file 'D:\Python\pythonProject\Bai` Hoc\DoCsangDoF\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 274)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditdoF = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditdoF.setGeometry(QtCore.QRect(200, 30, 261, 41))
        self.lineEditdoF.setObjectName("lineEditdoF")
        self.lineEditdoC = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditdoC.setGeometry(QtCore.QRect(200, 140, 261, 41))
        self.lineEditdoC.setObjectName("lineEditdoC")
        self.pushButtonConvert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConvert.setGeometry(QtCore.QRect(280, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonConvert.setFont(font)
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Fahrenheit (F) :"))
        self.label_2.setText(_translate("MainWindow", "Celsius (C) :"))
        self.pushButtonConvert.setText(_translate("MainWindow", "Convert"))
