# Form implementation generated from reading ui file 'D:\Python\pythonProject\Bai` Hoc\PhuongTrinh\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 530)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/kien0/OneDrive - zxcvb/Pictures/siu.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTen = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTen.setGeometry(QtCore.QRect(20, 20, 751, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTen.setFont(font)
        self.labelTen.setStyleSheet("background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 85, 255);")
        self.labelTen.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTen.setObjectName("labelTen")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 91, 41))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lineEditNhapN = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditNhapN.setGeometry(QtCore.QRect(140, 110, 461, 51))
        self.lineEditNhapN.setObjectName("lineEditNhapN")
        self.labelKetQua = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelKetQua.setGeometry(QtCore.QRect(50, 250, 81, 31))
        self.labelKetQua.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.labelKetQua.setObjectName("labelKetQua")
        self.lineEditKetQua = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditKetQua.setGeometry(QtCore.QRect(140, 250, 461, 51))
        self.lineEditKetQua.setObjectName("lineEditKetQua")
        self.pushButtonGiai = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonGiai.setGeometry(QtCore.QRect(70, 370, 111, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/kien0/OneDrive - zxcvb/Pictures/banhrang.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonGiai.setIcon(icon1)
        self.pushButtonGiai.setObjectName("pushButtonGiai")
        self.pushButtonTiep = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTiep.setGeometry(QtCore.QRect(290, 370, 111, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/kien0/OneDrive - zxcvb/Pictures/cuctay.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTiep.setIcon(icon2)
        self.pushButtonTiep.setObjectName("pushButtonTiep")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(520, 370, 111, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/kien0/OneDrive - zxcvb/Pictures/dauX.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon3)
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TranDucTrungKien"))
        self.labelTen.setText(_translate("MainWindow", "Con Cho Thanh Thinh"))
        self.label_2.setText(_translate("MainWindow", "Nhập N:"))
        self.labelKetQua.setText(_translate("MainWindow", "Kết quả:"))
        self.pushButtonGiai.setText(_translate("MainWindow", "Giải"))
        self.pushButtonTiep.setText(_translate("MainWindow", "Tiếp"))
        self.pushButtonExit.setText(_translate("MainWindow", "Thoát"))
